// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  lat: __t.f32(),
  lng: __t.f32(),
  population: __t.u64(),
  v0: __t.u8().name("v_0"),
  v1: __t.u8().name("v_1"),
  v2: __t.u8().name("v_2"),
  v3: __t.u8().name("v_3"),
  v4: __t.u8().name("v_4"),
  v5: __t.u8().name("v_5"),
  v6: __t.u8().name("v_6"),
  v7: __t.u8().name("v_7"),
  v8: __t.u8().name("v_8"),
  v9: __t.u8().name("v_9"),
  v10: __t.u8().name("v_10"),
  v11: __t.u8().name("v_11"),
  v12: __t.u8().name("v_12"),
  v13: __t.u8().name("v_13"),
  v14: __t.u8().name("v_14"),
  v15: __t.u8().name("v_15"),
  v16: __t.u8().name("v_16"),
  v17: __t.u8().name("v_17"),
  v18: __t.u8().name("v_18"),
  v19: __t.u8().name("v_19"),
});
