// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const City = __t.object("City", {
  id: __t.u64(),
  name: __t.string(),
  lat: __t.f32(),
  lng: __t.f32(),
  population: __t.u64(),
  v0: __t.u8(),
  v1: __t.u8(),
  v2: __t.u8(),
  v3: __t.u8(),
  v4: __t.u8(),
  v5: __t.u8(),
  v6: __t.u8(),
  v7: __t.u8(),
  v8: __t.u8(),
  v9: __t.u8(),
  v10: __t.u8(),
  v11: __t.u8(),
  v12: __t.u8(),
  v13: __t.u8(),
  v14: __t.u8(),
  v15: __t.u8(),
  v16: __t.u8(),
  v17: __t.u8(),
  v18: __t.u8(),
  v19: __t.u8(),
});
export type City = __Infer<typeof City>;

export const CityLanguage = __t.object("CityLanguage", {
  id: __t.u64(),
  cityName: __t.string(),
  language: __t.string(),
});
export type CityLanguage = __Infer<typeof CityLanguage>;

export const ScoreResult = __t.object("ScoreResult", {
  id: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  lat: __t.f32(),
  lng: __t.f32(),
  population: __t.u64(),
  score: __t.f32(),
  normScore: __t.f32(),
  colorR: __t.u8(),
  colorG: __t.u8(),
  colorB: __t.u8(),
});
export type ScoreResult = __Infer<typeof ScoreResult>;

export const Translation = __t.object("Translation", {
  id: __t.u64(),
  langCode: __t.string(),
  key: __t.string(),
  value: __t.string(),
});
export type Translation = __Infer<typeof Translation>;

